### ISSUE TITLE
Should augmented classes have a different grammar, so the name is a type annotation?

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#2085]
I noticed this when getting the data class example running, to see what the augmentation file looks like. I end up with things like this today, because we naively prefix all identifiers:

```dart
augment class i0.MyClass { // Error for `i0.MyClass` here, it just expects a name
  i0.MyClass copyWith({
    i1.bool? myString,
    i1.bool? myBool,
  }) => i0.MyClass(
        myString: myString ?? this.myString,
        myBool: myBool ?? this.myBool,
      );
}
```

I could change the logic to not use the _identifier_ for MyClass in that position, and just use `MyClass`, or we could allow it to do the prefix there since it really is a type annotation and not a name for a new class.

**Comment by munificent** [comment]
No, the name should definitely be a simple name. The merging process for augmentations is deliberately purely syntactic. We line up which class an augmenting class augments just by looking at its bare name. This is necessary because we need to be able to merge augmentations *before* identifiers in the main and augmentation libraries are resolved... because the augmentations themselves affect how identifiers are resolved.

**Comment by jakemac53** [comment]
The only real issue I have with that is it implies to me one of a few things:

- The primary library should be implicitly imported, with no prefix
- The primary library must be explicitly imported, and it must have no prefix (although `show` could be used)
- The name of the class is a bare string and isn't actually resolved to the original class?
- We need some other special case mechanism for resolving these names back to the augmented declaration, even when that library is not imported?

I think it should be something that is resolved to the actual class it is augmenting, and IDEs should allow you to navigate to that declaration. It isn't a _new_ type that is being declared, it's a type that is augmenting a known, existing type.

**Comment by munificent** [comment]
> * We need some other special case mechanism for resolving these names back to the augmented declaration, even when that library is not imported?

That's what the augmentation library proposal defines. It says:

1. An augmentation library must have a directive to specify which main library it augments.
2. An augmenting declaration (i.e. a declaration with the `augment` modifier) is matched up the corresponding declaration in the main library using its simple name.

Augmentations exist at a point in the compilation process before things like "name resolution" are meaningful, so it has its own very simple "matching" logic.

**Comment by jakemac53** [comment]
Ah ok, makes sense then
