### ISSUE TITLE
[patterns] Ambiguous invocation keys, caller-side checks, and soundness

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2931]
[Edit: The main topic here turned out to be the soundness of getter invocations, including a need to have "caller-side checks" on cached values. Adjusted the title accordingly.]

Cf. this section in the patterns feature specification: https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#side-effects-and-exhaustiveness.

I'm wondering whether it's a problem that some invocation keys can be identical, as far as I can see, in spite of the fact that they correspond to completely different invocations...?

For example, we could have the following:

```dart
class A {
  String get length => 'About average!';
}

bool get b {...}

void main() {
  Object o = b
      ? A()
      : b
          ? [1]
          : (length: true, width: false);

  // Invocation key for `o`: `("this", [])`, denoted by `root`.
  // For `A(length: Object x)`: `root : ("length", [])`.
  // For `(length: Object x, width: _)`: `root : ("length", [])`, `root : ("width", [])`.
  // For `[Object x]`: `root : ("length", [])` and `root : ("[]", [0])`.
  switch (o) {
    case A(length: Object x) || (length: Object x, width: _) || [Object x]:
      print(o);
  }
}
```

The invocation keys `root : ("length", [])` denote an invocation of the getter `length` in class `A`, an invocation of the record field getter `length`, or the `length` getter on the list.

I think this could actually be semantically benign, because there is no successful match whereby that invocation key would be associated with invocations of different members: No object can be a record and an `A` at the same time. It could be a `List` and an `A` at the same time, but we would then invoke the same getter named `length`, both in the case where the static type is `List<...>` and in the case where the static type is `A`.

We might encounter a typing conflict:

```dart
class A1 {
  bool operator >(int i) => false;
}

class A2 {
  bool operator >(int i) => true;
}

class B extends A1 implements A2 {}

class C1 {
  A1 get g {
    print('C1.g');
    return A1();
  }
}

class C2 {
  A2 get g {
    print('C2.g');
    return A2();
  }
}

class C extends C1 implements C2 {
  B get g {
    print('C.g');
    return B();
  }
}

void foo(Object o) {
  switch (o) {
    case C1(g: > 0) || C2(g: > 0):
      print('Match');
  }  
}

void main() {
  foo(C1());
  foo(C2());
  foo(C());
}
```

This program produces the following output (using current dart-pad, master channel):

```
C1.g
C2.g
Match
C.g
```

This works as expected for the `C1` (which isn't a `C2`) and for the `C2` (which isn't a `C1`), but with the `C` (which is both), we are apparently evaluating the `g` getter on the (confirmed) `C1`, obtaining an `A1`; and then reusing that result during the matching with `C2`, even though the `C2` has a `g` whose return type is `A2`, which is a type that has no relationship with `A1`.

Amazingly, it does work! In particular, there is only one invocation of `g` in the execution of `foo(C())`.

However, I'm puzzled how the type conflict can be overcome, and I'm wondering whether there are any soundness issues, if someone is able to come up with a really smart example. ;-)

@dart-lang/language-team, WDYT? Is this just "obviously there is no problem here!", or does it make you wonder a little bit, too?

@johnniwinther, @scheglov, this looks like pure magic, how did you do it? ;-)

**Comment by lrhn** [comment]
I think it works because we don't statically type the cached values. We don't need to, not unless we try to desugar it to typed Dart variables ... so let's not do that.

The caching works because no matter how many interfaces an object implements, it only has one *implementation*, which is known to satisfy *all* the interfaces.

When we've read a value from an object's getter once, we know that it's valid for all current and future interfaces that we match the object against. 
We don't need to remember anything about the type of that value.
The next time we need the value of a getter with that name, through any interface, we see that it has already been found, and can immediately and blindly treat it as satisfying the return type of the current interface, without any further checks. It must be valid, it was returned by the getter of an object implementing that interface!


Exhaustiveness doesn't care about caching, except to allow it to assume consistency between checks of the same value. It's done at compile-time, so the actual values doesn't matter, *any* valid and consistent value works.
Caching provides consistency, not typing. The typing comes from the current pattern that the getter is accessed from.

**Comment by johnniwinther** [comment]
We consider this case in the lowering, having one (untyped) cache variable for different accesses of the same invocation key. For instance `List.length` and `Map.length` on the same receiver - which could happen.

**Comment by eernstg** [comment]
@johnniwinther wrote:
> We consider this case in the lowering, having one (untyped) cache variable for different accesses of the same invocation key.

Interesting! Presumably there can be a cast which is marked "no need to check this at run-time".

However, one thing came up:

@lrhn wrote:
> _worry about contravariant generic returns_

Sounds like that's right!

Here's the "contravariant return type" example. It doesn't involve any ambiguous invocation keys, but it does show a soundness issue:

```dart
abstract class A<X> {
  String Function(X) get g;
}

class B implements A<int> {
  String Function(int) get g => (int i) => '$i';
}

void foo(Object o) {
  switch (o) {
    case A<num>(g: var f):
      // Not sound:
      print([f].runtimeType); // Static type of `f`: `String Function(num)`.
      print(f.runtimeType); // Dynamic type of `f`: `String Function(int)`.
      // Invocation throws:
      print('Match: ${f(25.7)}');
  }
}

void main() {
  foo(B());
}
```

This program incurs a run-time error:

```
JSArray<(num) => String>
(int) => String
Uncaught Error: TypeError: 25.7: type 'JSNumNotInt' is not a subtype of type 'int'
```

This is actually a soundness issue, because there is no dynamic type check at the point where the getter is invoked (and also not at the time where the cached value is reused), which means that we start executing the body of the case in `B.g` in a state where `f` has static type `String Function(num)` and run-time type `String Function(int)`.

I think the fix will be to introduce a caller-side check on the getter invocation, just like the caller-side check which is performed on a regular invocation on such getters.

**Comment by johnniwinther** [comment]
Yes, we need the caller-side checks for these. This currently not handled.

**Comment by lrhn** [comment]
So, basically, any time we need to read a getter/property, we should do what we usually would, with one extra step:

* Execute getter (where `operator[]` morally counts as a getter) to get a value *v*.
    *  Extra step: except if it's already cached, then use the cached value as *v* instead.
* If the return type of the getter requires a caller-side check, perform that check on *v*.
* Now we can trust that *v* satisfies the static return type of the getter and move on.

**Comment by eernstg** [comment]
> we can obviously cache the result of such a check too

That wouldn't work for the example I gave [here](https://github.com/dart-lang/language/issues/2931#issuecomment-1477441245): In `B(g: _)`, evaluation of `g` returns an object `o` whose static type is `String Function(int)`, and there is no caller-side check (because that type isn't "contravariant"), but later on we recognize that the getter which is consulted during matching of `A<num>(g: var f)` is the same getter as the `g` that we obtained `o` from. However, this time we need the value of the getter `A<num>.g`, not `B.g`, and `A<num>.g` needs a caller-side check.

So we can't reuse the result of the caller-side check, because there was no caller-side check at the time where `o` was obtained.

**Comment by lrhn** [comment]
The example *should* have a caller-side type check at the `A<num>(g: var f)` pattern.
First we check that the value is an `A<num>`, and succeeds.
Then we read the `g` getter of the object at static type `A<num>`.
The first step of that is to get the value of the `g` getter, which we already have, so we don't reinvoke the getter, we just reuse the cached value.
*Then* we do the caller-side type check on the value we "read", because `A<num>.g` has a covariant return type. 

We do that check at every getter access which needs it, even if we cached the actual value. (Unless we can somehow deduce that the test has been made before and succeeded, because a type check is guranteed side-effect free, so we can omit any type check that we can determine to be guaranteed to succeed, no matter how clever we are being.)


We can obviously only reuse the result of a caller-side type check if we
* know that it has already been performed, and
* it was testing for precisely what we need, or something stronger.

If we do multiple checks against the *same* type, we can remember whether it has already succeeded. Say
```dart
  case A<num>(g: var f) when f(0).length > 4: ...
  case A<num>(g: var f) when f(0).length > 2: ...
  case A<num>(g: var f) when f(0).length > 1: ...
```
Here each `g` fetch will need a caller-side type check, but after the first check has succeeded, we know that later checks will also succeed, and we don't need to do the same test again.

**Comment by eernstg** [comment]
Indeed. That's _exactly_ what I just said. ;-)

**Comment by munificent** [comment]
Sorry I'm replying late here. My GitHub inbox got away from me.

> WDYT? Is this just "obviously there is no problem here!", or does it make you wonder a little bit, too?

It definitely makes me wonder! It was never my intent when specifying the caching that you could end up having the same invocation key correspond to calls to different methods declared on different interfaces.

For Dart 3.0, I'm not too worried about the current behavior, assuming we insert whatever runtime checks are necessary for soundness. I think very few users will run into this in any noticeable way.

But, going forward, I would be inclined to avoid this by making invocation keys specific to the interface that the invocation is resolved against. So in the original example, it would be something like:

```dart
  // Invocation key for `o`: `("this", [])`, denoted by `root`.
  // For `A(length: Object x)`: `root : ("A.length", [])`.
  // For `(length: Object x, width: _)`: `root : ("(Object,Object?).length", [])`, `root : ("width", [])`.
  // For `[Object x]`: `root : ("List.length", [])` and `root : ("[]", [0])`.
  switch (o) {
    case A(length: Object x) || (length: Object x, width: _) || [Object x]:
      print(o);
  }
```

This might mean more redundant calls in some unusual cases, but would eliminate the need for any runtime checks.

**Comment by lrhn** [comment]
I think the current behavior is correct, and changing it could very well be wrong.

I don't want to make extension keys depend on interface. Every *interface*/virtual member with the same name *is* the same getter, no matter which interface type it's accessed from. The value must only be read once.
It might need to be type-checked more than once, but that could be a second layer of caching, if we don't want to do the same type check multiple times (but again, that can be a compiler-optimization, as long as we only read the getter once).

Every *non-virtual* getter should be cached based on the implementation it actually calls, which is what is happening today for extension members. We'll do something similar for inline class members too. In these cases we can determine precisely which member is invoked (and the type it's invoked on, since static binding of type parameters also matters).

**Comment by eernstg** [comment]
The current behavior is not quite correct, we're not supposed to have soundness issues:

```dart
abstract class A<X> {
  void Function(X) get g;
}

class B implements A<int> {
  void Function(int) get g => (int i) => i.isEven;
}

void foo(Object o) {
  switch (o) {
    case B(g: _) && A<num>(g: var f): f(25.7);
  }
}

void main() => foo(B());
```

The program has no errors according to the analyzer and CFE, but it runs and reaches the body of the function literal in a state where the formal parameter `i` has static type `int` and an actual value of type `double`.

So we _do_ need to introduce a getter-side check on cached values in the case where they "have a contravariant type".

**Comment by lrhn** [comment]
Agree. The type checking is necessary for soundness, as https://github.com/dart-lang/language/issues/2931#issuecomment-1477099046 also stated. It's apparently still not handled.

**Comment by munificent** [comment]
Filed an implementation issue to track inserting the runtime checks: https://github.com/dart-lang/sdk/issues/52192

**Comment by eernstg** [comment]
Closing: The issues that came out of this discussion have been handled in https://github.com/dart-lang/sdk/issues/52192.
