### ISSUE TITLE
To-non-nullable indicator for type parameters like `T!`

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/language#4160]
We can currently have a type parameter like `class Foo<T extends Object> {}` and specify a method to return `T?`:

```dart
class Foo<T extends Object> {
  T? foo() => null;
}
```

However we can't do this in the other way, meaning we have a `T extends Object?` and we want to specify a method to return a non-nullable version of `T`, I propose we add a `T!` variation so we can have:

```dart
class Foo<T extends Object?> {
  T! foo() => ...;
}
```

**Comment by lrhn** [comment]
I recommend doing:
```dart
class Foo<T extends Object> {
 T foo() => ...

  // use T? everywhere being nullable is allowed.
}
```

Even if we had a `!` operator that could be applied to type variables, it would not be able to make every type non-nullable.
For example `Foo<FutureOr<int?>>` would have a `foo()` that returns **NonNull**(`FutureOr<int?>`) which is `FutureOr<int?>` again.
That may not be a problem for the cases where it does work.

The `!` would  be a general operator on types. You probably can't write `int?!`, but only because it's redundant, so the only real use will be on type variables. (Again `FutureOr<T>!` will be `FutureOr<T>`, not `FutureOr<T!>`.)

**Comment by HosseinYousefi** [comment]
> I recommend doing:
> 
> ```dart
> class Foo<T extends Object> {
>  T foo() => ...
> 
>   // use T? everywhere being nullable is allowed.
> }
> ```

That's not an accurate. `Foo<String>` and `Foo<String?>` might indeed be different types to truly differentiate them I need to add a `FooOfNullable<T extends Object>` and `Foo<T extends Object> extends FooOfNullable<T>` and override the methods previously defined as `T?` to now return `T`. But this is ugly!

**Comment by lrhn** [comment]
It's not the same, and nothing is because the functionality your asking for doesn't exist. I often find that the rewrite gives a better design, because the type `T!` isn't what is really needed. (If `T` is generic in a way that allows a user to include `null` in it's values, why does the API remove `null`. That's not being _generic_ over the type `T`!)

Looking at it again, if the construct is going to work, the `!` probably has to be reified. The static and runtime type systems both contain types of the shape `T!`, just like they contain types of the shape `T?`.

Normalization would convert `T!!` and `T?!` to **Norm**`(T!`), `Null!` to `Never`, and `T!` to `Object` of `T` is a supertype of `Object` and to `T` if `T` is a subtype of `Object`.
(And `T!?` to **Norm**(`T?`).)

Subtyping would treat `T!` like the intersection type `T & Object` (which it is, it's the dual of `T?` being the union type `T | Null`, making a type non-nullable where `?` makes it nullable).

The _interface signature_ of `T!` is the interface signature of **NonNull**(`T`).

It introduces yet another special-cased type, like the union types `?` and `Future Or`. It does _fit_ with the `?` type, it's not completely arbitrary.

**Comment by TekExplorer** [comment]
I actually really like this.

Its a nice, intuitive mirror of the null-assert and null-aware operators

It can actually matter a lot when the type signature is meant to accept nullables, (more to the point, accept all types) but we can't actually accept/return null in some places, because null may have special meaning.

Only, that may not be the case for the _entire_ class, so then you're basically forced to accept a second non-null generic which just worsens the user experience.

At that point, your desired API may then need to be scrapped entirely and rewritten, which in some cases might be fine, but not always.

It would also make the oft-used `<T extends Object>` so much simpler with `<T!>` which is _way_ easier.

**Comment by munificent** [comment]
We discussed the idea of `!` on types heavily when non-nullable types were initially being designed. If I remember right, we ultimately decided that it wasn't useful enough to be worth doing. We couldn't think of many (any?) concrete, compelling use cases.

@HosseinYousefi, can you give us some more information about the real-world context where you find yourself wanting this feature? That will help us understand the motivation and value proposition.

**Comment by HosseinYousefi** [comment]
> @HosseinYousefi, can you give us some more information about the real-world context where you find yourself wanting this feature? That will help us understand the motivation and value proposition.

I personally never needed this when writing Dart code. I specifically want to be able to generate better bindings (using [jnigen](https://github.com/dart-lang/native/tree/main/pkgs/jnigen)) for Java sources that have this pattern: https://github.com/search?q=%22%40NonNull+T%22+language%3AJava+&type=code for example:

https://github.com/ProtocolSupport/ProtocolSupport/blob/1c6039b55e66b6da65a6ffa07f889c9fe3301c79/src/protocolsupport/utils/ThreadLocalObjectPool.java#L8-L19

Where some generic type parameter `T` is not defined as `@NonNull`, however somewhere a `@NonNull T` is either returned or expected as a parameter. A lot of times this is because the original code does not have the correct annotations on the type parameters but jnigen has to work with what's out there and `T!` correctly represent what is found in these Java sources.

**Comment by lrhn** [comment]
Looking at the Java examples, my immediate impression is that these should just use non-nullable types. They're either saying that the type parameter is `@NonNull`, meaning that all occurrences are effectively `@NonNull`, or the type parameters are not not marked, but all the parameters of those types are, so you can only really pass in non-`null` values (and therefore usually only take non-`null` values out).

Java's `@NonNull` is not the same as Dart's sound null-safety. I think the best you can do is to make all the types non-nullable, and then add `?`s only where absolutely needed.

**Comment by HosseinYousefi** [comment]
> I think the best you can do is to make all the types non-nullable, and then add `?`s only where absolutely needed.

`List<@NonNull Integer>` is still different than `List<Integer>`. I could use a heuristic when generating the bindings that if all of the instances of some type parameter `T` inside the class are annotated with `@NonNull` but the type parameter itself is not annotated at the time of declaration then assume `T` is also `@NonNull`.

**Comment by munificent** [comment]
> `List<@NonNull Integer>` is still different than `List<Integer>`.

Right, but I suspect the way to model those in Dart is:

```
Java:                         Dart:
List<@NonNull Integer>        List<int>
List<Integer>                 List<int?>
```

And not:

```
Java:                         Dart:
List<@NonNull Integer>        List<int!>
List<Integer>                 List<int>
```

**Comment by HosseinYousefi** [comment]
> > `List<@NonNull Integer>` is still different than `List<Integer>`.
> 
> Right, but I suspect the way to model those in Dart is:
> 
> ```
> Java:                         Dart:
> List<@NonNull Integer>        List<int>
> List<Integer>                 List<int?>
> ```
> 
> And not:
> 
> ```
> Java:                         Dart:
> List<@NonNull Integer>        List<int!>
> List<Integer>                 List<int>
> ```

Of course. I meant that we can't generally generate each generic class (phew! too many words starting with gen) as `Foo<T extends Object>` as you pointed out. Because we need `List<int?>`.

**Comment by HosseinYousefi** [comment]
Taking the example I randomly found on [github](https://github.com/ProtocolSupport/ProtocolSupport/blob/1c6039b55e66b6da65a6ffa07f889c9fe3301c79/src/protocolsupport/utils/ThreadLocalObjectPool.java#L8-L19):

```java
public class ThreadLocalObjectPool<T> {
        // ...
	public @Nonnull T get() {
		return pool.get().pop().object;
	}
}
```

Here I generate this class as:

```dart
class ThreadLocalObjectPool<T extends JObject?> extends JObject {
  //...
  T get() { /* ... */ } // The return type is `T` because we don't have `T!`
}
```

I know that the original code here actually meant to be (because it seems from the code that having any nullable type parameter here doesn't make sense)

```java
public class ThreadLocalObjectPool<@Nonnull T> {
        // ...
	public T get() {
		return pool.get().pop().object;
	}
}
```

and I would generate this correctly as:

```dart
class ThreadLocalObjectPool<T extends JObejct> extends JObject {
  // ...
  T get() { /* ... */ } // The return type is correct.
  // Also the Java code could have some @Nullable T foo() and we could
  // generate that correctly as T? foo() here.
}
```

I don't know if there is any legit reason in Java to have this pattern but the code you encounter can have this pattern. Is this reason enough to add a new language feature to Dart? Perhaps not, but that's for the language team to decide.

**Comment by HosseinYousefi** [comment]
I can contrive an example where this could be used – say if we want to add a `firstNonNull` getter to `Iterable<T>`:

```dart
extension on Iterable<T> {
  T! get firstNonNull => firstWhere((element) => element != null)!;
}
```

Again, I don't think I've ever needed this when developing Dart myself.

**Comment by mmcdon20** [comment]
@HosseinYousefi 

> I can contrive an example where this could be used – say if we want to add a `firstNonNull` getter to `Iterable<T>`:
> ```dart
> extension on Iterable<T> {
>   T! get firstNonNull => firstWhere((element) => element != null)!;
> }
> ```
> Again, I don't think I've ever needed this when developing Dart myself.

You can already write the following in current dart

```dart
extension<T> on Iterable<T?> {
  T get firstNonNull => firstWhere((element) => element != null)!;
}
```

**Comment by HosseinYousefi** [comment]
> You can already write the following in current dart

Cool, I didn't think about that! 

Well, if the getter/function is not in an extension but rather a method in the class itself you can't do it, right?

**Comment by mmcdon20** [comment]
> > You can already write the following in current dart
> 
> Cool, I didn't think about that!
> 
> Well, if the getter/function is not in an extension but rather a method in the class itself you can't do it, right?

~~I don't think it is possible in a class method (at least I can't think of a way to do it off the top of my head).~~ (see edit below)

As mentioned before it is possible when using an extension method.

Extension type should also work

```dart
extension type MyIterable<T>(Iterable<T?> items) {
  T get firstNonNull => items.firstWhere((element) => element != null)!;
}
```

Or function accepting the list as argument

```dart
T firstOrNonNull<T>(Iterable<T?> items) {
  return items.firstWhere((element) => element != null)!;
}
```
---

Edit 3: after a few attempts at trying to get it working with class methods, I don't think it is possible to achieve in current dart.

**Comment by HosseinYousefi** [comment]
> ```dart
> void main() {
>   final c = MyClass([null, null, 3, null, null]);
>   int res = c.firstOrNonNull();
>   print(res); // 3
> }
> ```
> It's a bit odd though, and it doesn't work with getters since you can't have a generic type argument in a getter.

This only works because you are providing the type `G` when declaring `res` as `int res`. If you let the type inference work you'd still get the nullable type:

```dart
final res = c.firstOrNonNull();
int anotherRes = res; // A value of type 'int?' can't be assigned to a variable of type 'int'.
```

**Comment by mmcdon20** [comment]
@HosseinYousefi Good catch, if you remove the `extends T` it no longer has this problem, but it has another problem where the user can explicitly provide an invalid type (which can fail the cast at runtime).

**Comment by HosseinYousefi** [comment]
> if you remove the `extends T` it no longer has this problem

If we remove `extends T` then it will just always return `dynamic`. Which of course can be assigned to anything but that's not type-safe anymore.

**Comment by mmcdon20** [comment]
@HosseinYousefi Good catch again. It wasn't showing any errors on dartpad, but I can see that this is the case when trying it in VSCode.

**Comment by mmcdon20** [comment]
@HosseinYousefi 

I have worked out a way to get it to work in classes via a `mixin`. See implementation below.

```dart
class _MyClass<T> {
  Iterable<T> items;
  _MyClass(this.items);
}

mixin _MyMixin<A> on _MyClass<A?> {
  A get firstNonNull => items.firstWhere((element) => element != null)!;
}

class MyClass<T> = _MyClass<T?> with _MyMixin<T>;

void main() {
  final c = MyClass([null, null, 3, null, null]);
  final res = c.firstNonNull;
  int anotherRes = res;
  print(anotherRes); // 3
}
```

**Comment by HosseinYousefi** [comment]
What you did here essentially makes `MyClass<int>` still accept `Iterable<int?>` (We also don't want this), so `c` is a `MyClass<int>` in this case. If we force it to be a `MyClass<int?>`, then `firstNonNull` will also return `int?`:

```dart
final c = MyClass<int?>([null, null, 3, null, null]);
final res = c.firstNonNull;
int anotherRes = res; // A value of type 'int?' can't be assigned to a variable of type 'int'.
```

> `class MyClass<T> = _MyClass<T?> with _MyMixin<T>;`

TIL you can write `class Foo = Bar with Baz`!

**Comment by mmcdon20** [comment]
If you want to prevent an explicit nullable type argument, you can do:

```dart
class MyClass<T extends Object> = _MyClass<T?> with _MyMixin<T>;
```

**Comment by HosseinYousefi** [comment]
> If you want to prevent an explicit nullable type argument, you can do:
> 
> class MyClass<T extends Object> = _MyClass<T?> with _MyMixin<T>;

The point of this issue is to have a class like `MyClass<T?>` that has a method that actually returns a `T!`. What you suggest completely blocks off the possibility of having a `MyClass<T?>`.

**Comment by mmcdon20** [comment]
In that case I am out of ideas. I don't know that it can be made to work for a class (without using extensions).,

**Comment by HosseinYousefi** [comment]
> In that case I am out of ideas. I don't know that it can be made to work for a class (without using extensions).,

That said I'm not sure if having all the methods of a Java class in extensions actually that bad of an idea because they really are just calling Java. 

Extensions are resolved statically but they call the same Java function which gets resolved in a polymorphic way so that's not a problem for my use case.

**Comment by lrhn** [comment]
I can't find a good specification for Java's `@NotNull`. It's just, like, an annotation, so you have to have some validator to give it meaning. (I can't find any online Java editor that can `import jakarta.annotation`, so it's not easy to do a quick check.)

I have a hunch that `MyClass` and `@NotNull() MyClass` are not completely equivalent to Dart's `MyClass?` and `MyClass`, because there is no runtime type in Dart to represent `MyClass`.

If you write 
```java
class MyClass<@NotNull() T extends Integer> {
  T repeat(T value) { return value; } 
}
```
then the only type argument you can pass is `Integer`, because that is the only actual type that exists, `@NotNull()` is not a type, it cannot be a type argument. 
Making the type parameter `@NotNull()` just means that all occurrences of it are automatically `@NotNull()` too.
If so the class above is completely equivalent to:
```java
class MyClass<T extends Integer> {
  @NotNull() T repeat(@NotNull() T value) { return value; } 
}
```

If that is true, then you should compile both interfaces in the same way.
I would expect that the *most precise* compilation of the Java behavior to Dart is to make all type parameters non-nullable, and make all occurrences of the type parameters (other than as type arguments) be nullable (`T?`) if they would be in Java, and plain (`T`) if they would be `@NotNull() T` in Java.

That is, keep the nullability out of the type parameters, because Java doesn't *have* separate `Integer` and `Integer?` that it can use as type arguments.

(If the `@NotNull()` validator is smarter than that, and prevents you from using a `<T extends Integer>` as argument to a `<T extends @NotNull() Integer>`, then you might need both.)

In general, in Dart, needing a "Make type non-nulllable" operator is usually a sign that you should have made a type parameter non-nullable earlier. That may go quite far back in some cases. Generics, and the type system in general, is not really designed for an operation like "make non-nullable".

Generics, type parameters, are designed to allow you to *remember a type* throughout an otherwise generic computation, where an input value of that type eventually becomes an output value of that type. Every value of every type parameter binding is treated the same generic way, without being distinguished. The code is *generic*, it works for multiple types, without needing to be specialized.

If a type parameter type is nullable, it means that `null` is one of the values it should be working generically on, and you shouldn't be distinguishing `null` and treating it specially.
If you do, you're acting like you really have a `T?`, which just happens to have a nullable `T`, and are ignoring that
the `null` could also be a value that should be treated generically. That's why you can promote from `T?` to `T`.
But in good generic code, you should never _care_ whether a type parameter `T` is bound to a nullable type or not, it's all data to be treated generically.

**Comment by mraleph** [comment]
> I can't find a good specification for Java's `@NotNull`.

That's because `javax.annotation.Nonnull` (notice: _Non_, not _Not_) is (I think) effectively dead: it came with JSR-305 which is dormant. The closest modern alternative is [this JEP](https://openjdk.org/jeps/8303099), which comes with custom syntax.

There is 1001 different versions[^1] of this annotation, and the semantics indeed depends on the particular tool you use with them - and some of these are not even allowed on type parameters. 


[^1]: You can see a list of annotations [in IDEA docs](https://www.jetbrains.com/help/idea/annotating-source-code.html#notnull).

**Comment by lrhn** [comment]
I think `javax.annotation.contraints.NotNull` existed at some point (Java 8-11 or something), and was moved to `jakarta.validation.constraints.NotNull` where it [still exists](https://jakarta.ee/specifications/bean-validation/3.0/apidocs/jakarta/validation/constraints/notnull. It was *possibly* related to JSR 308.

The examples here were indeed using `@Nonnull`, so that name was still something I dreamt up.
(My answer still stands, you need to know the exact semantics of the `@Nonnull` you are trying to migrate, and I expect they'll be best matched by a non-nullable type parameter and `?` on some (or even all) occurrences.

**Comment by HosseinYousefi** [comment]
> That is, keep the nullability out of the type parameters, because Java doesn't have separate Integer and Integer? that it can use as type arguments.

I mean at runtime the only type argument is `Object`! It would be weird to solely have a `JList<JInteger>` that has an `operator []` that returns a `JInteger?`. It's much cleaner to have both and `operator []` returns `T` for both nullabilities of `T`.

The way I'm treating the annotations is just mirroring what the Kotlin compiler does: https://kotlinlang.org/docs/java-interop.html#nullability-annotations. Of course Kotlin has a concept of "platform types" but in Dart we default to nullable types whenever we're not explicitly provided with an annotation.
