### ISSUE TITLE
Type unsafety of ??

### ISSUE THREAD

**Issue by duzenko** [dart-lang/language#465]
Consider the following code
```
    num n = 1;
    String s = n ?? List();
````
It gives an obvious runtime error.
I'm not so much interested in why it's considered a valid syntax as in getting the analyzer report this at compile time. I have bumped into this a few times too many.

**Comment by srawlins** [comment]
I suspect this is an implicit cast. The same thing could be done with:

```dart
num n = 1;
String s = n == null ? List() : n;
```

The type of the right-hand-side is the Least Upper Bound of `List<dynamic>` and `num`, which is Object. So an Object is being assigned to a String, via an implicit downcast. See https://github.com/dart-lang/sdk/issues/31410 for some history. This is going away with the Non-nullable type system. You can also ban it from your codebase with `implicit-casts: false` in your `analysis_options.yaml`.

**Comment by duzenko** [comment]
> 
> 
> I suspect this is an implicit cast. The same thing could be done with:
> 
> ```dart
> num n = 1;
> String s = n == null ? List() : n;
> ```
> 
> The type of the right-hand-side is the Least Upper Bound of `List<dynamic>` and `num`, which is Object. So an Object is being assigned to a String, via an implicit downcast. See [dart-lang/sdk#31410](https://github.com/dart-lang/sdk/issues/31410) for some history. This is going away with the Non-nullable type system. You can also ban it from your codebase with `implicit-casts: false` in your `analysis_options.yaml`.

Sorry, I think `implicit-casts: false` is a bit of a overreaction to such a localized issue.

**Comment by munificent** [comment]
Closing this because it will get addressed by NNBD which removes implicit downcasts.

**Comment by natebosch** [comment]
> Closing this because it will get addressed by NNBD which removes implicit downcasts.

This case _won't_ be fixed assuming we continue to allow implicit downcast from `dynamic`.

https://github.com/dart-lang/language/issues/192#issuecomment-591662579

**Comment by duzenko** [comment]
reopen?

**Comment by natebosch** [comment]
Hmm, trying to repro I'm seeing that the type of `n ?? List()` is `Object` and not `dynamic` like I thought, so this case will indeed be solved.

**Comment by leafpetersen** [comment]
This is mostly solved.  The case that isn't solved is if one of elements of the lub is `dynamic`.

```dart
void main() {
  dynamic y;
  int x = y ?? "hello";
}
```

**Comment by duzenko** [comment]
No, `dynamic` is not a problem
